### ISSUE TITLE
Get nan after 450 epochs

### ISSUE THREAD

**Issue by zclzcl0223** [Suchun-sv/SGDD#1]
Based on the given codes, datasets and parameter settings. I ran 'python train_SGDD.py --dataset cora  --nlayers=2 --beta 0.1 --r=0.5 --gpu_id=0' but the loss_avg and the loss of training gcn model became 'nan' after training the synthetic data for 450 epochs.  Do I miss some important Steps? The following is my training log.
[cora.txt](https://github.com/RingBDStack/SGDD/files/13424117/cora.txt)

**Comment by Suchun-sv** [comment]
Thanks for your interests of our work, I repeat the code and got non-nan results, could you please replay your code with simple adjustments (e.g., changing your random seed). Feeling free for providing your env by running "pip freeze" for us debugging?
<img width="921" alt="image" src="https://github.com/RingBDStack/SGDD/assets/35399433/8f82ee48-6460-440c-a9b6-672467de7215">
