### ISSUE TITLE
Additional requirement

### ISSUE THREAD

**Issue by Jaykakkad82** [Suchun-sv/SGDD#3]
Hi,

Thank you for this excellent work. 

I am trying to run the code by creating an environment provided in your requirement.txt (which I guess is similar to Gcond environment). However, it seems there are additional packages required. Request you to please share version/ installations for :

a) dgl (recent version does not work)

b) chardet

c) For the torch geometric version (torch_geometric==1.6.3) provided in requirements.txt, i get the following error:
_ImportError: cannot import name 'StochasticBlockModelDataset' from 'torch_geometric.datasets'_
Are you using a different version of torch_geometric? Pls help me in resolving the error.

Looking forward to your response.

Many thanks.

**Comment by Jaykakkad82** [comment]
One more question related to the environment requirement. 
I commented out the import of dgl.dataset so that the code can run for cora dataset. But I get below error:
  _File "/data/SGDD/models/IGNR.py", line 40, in __init__
    nn.Linear(in_, out_, dtype=dtype),
TypeError: __init__() got an unexpected keyword argument 'dtype'_

When I saw the torch 1.7.0 documentation, it seems dtype cannot be used. Please check below link:
https://pytorch.org/docs/1.7.0/generated/torch.nn.Linear.html#torch.nn.LinearW\

So, are you using a different version of torch? 
Pls let us know. 
Thanks.

**Comment by Suchun-sv** [comment]
Thanks for your attention to our work, I have sent the requirements settings to you. Hope that could help you~
